server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-mall?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000

wechat:
  appId:
  secret:
  mchId:
  paySign:
  tradeType: JSAPI
  requestUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  notifyUrl:
  orderQueryUrl: https://api.mch.weixin.qq.com/pay/orderquery
  certName: /cert/apiclient_cert.p12
  refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  refundQueryUrl: https://api.mch.weixin.qq.com/pay/refundquery


